jwt:
  secret-key: secret-key-one-two-dear-my-x-it-will-be-change-next-time
  token-validity-in-sec: 32400
  refresh-token-validity-in-sec: 604800

access-id: server-access-id
access-key: server-access-key